# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0002_auto_20170513_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Wine', (('whitewine', 'White Wine'), ('redwine', 'Red Wine'), ('rosewine', 'Rose Wine'), ('dessertwine', 'Dessert Wine'), ('sparkling', 'Sparkling Wine'))), ('Spirits', (('whisly', 'Whisky'), ('vodka', 'Vodka'), ('gin', 'Gin'), ('brandy', 'Bbrandy'), ('tequila', 'Tequila'), ('liqueur', 'Liqueur'), ('rum', 'Rum'), ('aperitif', 'Aperitif'))), ('Beer', (('ale', 'Ale'), ('lager', 'Lager'), ('ipa', 'Ipa'), ('stouts', 'Stouts'), ('blondes', 'Blondes'), ('paleales', 'Pale Ales'), ('wheatbeer', 'Wheat Beer'), ('aleandporters', 'Ale and Porters'), ('whisky:bourbonbarrel-agedstouts', 'Whisky:Bourbon Barrel-Aged Stouts'), ('redales:ambers', 'Red Ales:Ambers'), ('ryesandpumpkinales', 'Ryes and pumpkin Ales'), ('pilsners', 'Pilsners'), ('amberlager', 'Amber Lager'), ('bock', 'Bock'), ('dunkel', 'Dunkel'), ('schwarzbier', 'Schwarzbier')))], max_length=100),
        ),
    ]
