# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0003_auto_20170513_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='category',
            new_name='typedrink',
        ),
    ]
