# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0004_auto_20170513_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Wine', 'Wine'), ('Spirits', 'Spirits'), ('Beer', 'Beer')], default='Wine', max_length=100),
        ),
    ]
