# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0006_auto_20170516_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('people', models.CharField(max_length=2)),
                ('time', models.CharField(choices=[('19.00', '19.00'), ('19.30', '19.30'), ('20.00', '20.00'), ('20.30', '20.30'), ('21.00', '21.00')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='booking',
        ),
        migrations.AddField(
            model_name='bar',
            name='book',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkMe.Bar'),
        ),
    ]
