# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0007_auto_20170522_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='book',
            new_name='capacity',
        ),
    ]
