# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkMe', '0010_auto_20170522_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='content',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
